# Generated by Django 4.0.4 on 2022-05-22 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.TextField()),
                ('team2', models.TextField()),
                ('status', models.TextField()),
                ('winner', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bettor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=4, max_digits=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('bettor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='betting.bettor')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='betting.game')),
            ],
        ),
    ]
