# Generated by Django 4.0.4 on 2022-05-22 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='odds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TotalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, max_digits=4)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='betting.game')),
            ],
        ),
    ]
