# Generated by Django 4.0.4 on 2022-05-22 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_bet_odds_totalline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TOTAL', 'Total'), ('ML', 'Moneyline'), ('SPREAD', 'Spread')], max_length=15)),
                ('points', models.DecimalField(decimal_places=2, max_digits=4)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=4)),
                ('side', models.CharField(choices=[('OVER', 'over'), ('UNDER', 'under')], max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='betting.game')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField()),
                ('name', models.TextField()),
                ('sport', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='TotalLine',
        ),
        migrations.AddField(
            model_name='line',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='betting.team'),
        ),
        migrations.AddField(
            model_name='bet',
            name='line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='betting.line'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_1', to='betting.team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_2', to='betting.team'),
        ),
    ]
