# Generated by Django 4.0.4 on 2022-05-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0005_bet_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='odds',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='line',
            name='side',
            field=models.CharField(blank=True, choices=[('OVER', 'over'), ('UNDER', 'under')], max_length=10),
        ),
    ]
