# Generated by Django 4.0.4 on 2022-05-22 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0006_alter_line_odds_alter_line_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='betting.team'),
        ),
    ]
